apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp
  namespace: openshift-gitops
spec:
  project: infra-neutron
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.0
    helm:
      releaseName: hashicorp-vault
      valueFiles:
      - $values/gitops/hashicorp/argocd/values.yaml  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: neutron-it
