---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: ansible-automation-platform-operator
    namespace: aap-lab
spec:
  channel: stable-2.4-cluster-scoped
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: aap-operator.v2.4.0-0.1720482740
