kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-8ada74f2-8863-4df8-8db1-aed5d79949ac
  storageClassName: lvms-vg1
  volumeMode: Filesystem