apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: documenso-console-link
spec:
  applicationMenu:
    imageURL: https://upload.wikimedia.org/wikipedia/commons/e/ec/Etikimza_logo_icon.png
    section: documenso console link
  href: https://neutron-documenso.apps.neutron-sno-gpu.neutron-it.fr
  location: ApplicationMenu
  text: Documenso
