apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap
  namespace: openshift-gitops
spec:
  project: infra-neutron
  source:
    repoURL: https://github.com/neutron-IT-organization/infra-neutron.git
    targetRevision: main
    path: gitops/minio/base
  destination:
    server: https://kubernetes.default.svc
    namespace: neutron-it
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
