apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-studio
  labels:
    app: label-studio

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: label-studio
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - "label-studio"
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: label-studio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: label-studio
subjects:
- kind: ServiceAccount
  name: label-studio