apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sonarqube
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sonarqube
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 75
          type: Utilization
