apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-neutron
  namespace: openshift-gitops
spec:
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
